<?php
/**
 * AdditionalAdvancedScanInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * virusapi
 *
 * The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * AdditionalAdvancedScanInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Additional non-threat content verification information
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditionalAdvancedScanInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdditionalAdvancedScanInformation"
     */
    public function testAdditionalAdvancedScanInformation()
    {
    }

    /**
     * Test attribute "contains_json"
     */
    public function testPropertyContainsJson()
    {
    }

    /**
     * Test attribute "contains_xml"
     */
    public function testPropertyContainsXml()
    {
    }

    /**
     * Test attribute "contains_image"
     */
    public function testPropertyContainsImage()
    {
    }
}
